### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by lucasew** [lucasew/jogo_da_velha_online#1]
# Frontend
- [x] Tela inicial
- [x] Template do histórico
- [x] Tela do board
- [x] Tela para criar conta
# Backend
- [x] Criar o projeto
- [ ] Implementar o esquema de segurar conexão (estratégia rapidleech)
  - Esse pacote da stdlib suporta: com.sun.net.httpserver ([doc](https://docs.oracle.com/javase/8/docs/jre/api/net/httpserver/spec/index.html))
- [ ] Regra de negócio do jogo da velha (validação de estados)
- [ ] Event loop de jogadas
- [ ] Pareamento de partidas
# Backend + persistência
- [x] Cadastro de usuários
- [ ] Persistência do resultado das partidas (aplicar como uma transação)
# Documentação
- [ ] Segue a sequência do doc, link na desc do grupo, depois que terminar a gente decide se sobe no git também

# Prazo
16 de Abril
